### ISSUE TITLE
Enable user specification of rank in filter_taxa.rule

### ISSUE THREAD

**Issue by brooksph** [dahak-metagenomics/dahak-taco#1]
@kternus pointed out that the current protocol generates reports at the genus rank with ```-r genus```. We should enable the user to choose any taxonomic rank in the the taxonomic classification workflow by modifying the filter_taxa.rule.

**Comment by brooksph** [comment]
Same functionality should be enabled in the kaiju2krona.rule

**Comment by charlesreid1** [comment]
Great! Thanks for the feedback! Since workflow steps share a lot of the same parameters, I've moved all parameters for a given workflow into a single .settings file, so it's a one-stop place to see what configuration options a user has. So, I'll add a `taxonomic_rank` option to [`taxonomic_classification.settings`](https://github.com/charlesreid1/dahak-taco/blob/master/rules/taxonomic_classification/taxonomic_classification.settings)

**Comment by charlesreid1** [comment]
By the way, I should mention that organizing things into .rule and .settings files makes it pretty trivial to convert any hard-coded argument into a user-defined argument. For example, here's the commit where I added the `taxonomic_rank` option. It only took 3 lines! (well, 5 including `{}`s): 

Commit: 7e00ddf2e3a5883a9f7e5eb8e7378d99d44b932b
